import os
import pandas as pd
import numpy as np

# ================= CONFIGURATION =================
# Define paths relative to the project root
BASE_DIR = os.getcwd()
RAW_DIR = os.path.join(BASE_DIR, "shared", "raw")
REPORT_DIR = os.path.join(BASE_DIR, "shared", "reports")

# Input File (Generated by swaggerscrapper.py)
# Note: The previous step config named this "Extraction.xlsx"
INPUT_FILE = os.path.join(RAW_DIR, "Extraction.xlsx") 

# Output File
OUTPUT_FILE = os.path.join(REPORT_DIR, "Pl_SOURCEvsTARGET_Metadata_Comparison.xlsx")

def compare_endpoints():
    print("Starting Endpoint Comparison Script...")
    print(f"Reading Input: {INPUT_FILE}")

    if not os.path.exists(INPUT_FILE):
        print(f"❌ Error: Input file not found at {INPUT_FILE}")
        return

    # 1. Load Data
    try:
        df_source = pd.read_excel(INPUT_FILE, sheet_name="SOURCE")
        df_target = pd.read_excel(INPUT_FILE, sheet_name="TARGET")
    except ValueError as e:
        print(f"❌ Error reading sheets: {e}")
        print("Ensure 'Extraction.xlsx' has 'SOURCE' and 'TARGET' sheets.")
        return

    # 2. Normalize & Fill NaNs for cleaner comparison
    df_source = df_source.fillna("").astype(str)
    df_target = df_target.fillna("").astype(str)

    # 3. Align Columns (Handle dynamic parameters)
    # Find all unique parameter columns across both sheets (excluding Endpoint)
    all_cols = set(df_source.columns) | set(df_target.columns)
    all_cols.discard("Endpoint")
    parameter_cols = sorted(list(all_cols))

    print(f"Comparing {len(df_source)} Source endpoints vs {len(df_target)} Target endpoints.")

    # 4. Merge Dataframes on 'Endpoint'
    # 'outer' merge ensures we catch endpoints missing in either side
    merged = pd.merge(
        df_source,
        df_target,
        on="Endpoint",
        how="outer",
        suffixes=('_SOURCE', '_TARGET'),
        indicator=True
    )

    # 5. Determine Presence Status (User Requirement: FOUND / MISSING logic)
    # We map the pandas '_merge' indicator to business terms
    status_map = {
        "left_only": "Only in SOURCE (Missing in TARGET)",
        "right_only": "Only in TARGET (New/Extra)",
        "both": "Present in Both"
    }
    merged["Presence_Status"] = merged["_merge"].map(status_map)

    # 6. Content Comparison Logic (For endpoints present in both)
    # We want to check if the parameters (enums) are identical
    
    def check_content_match(row):
        if row["_merge"] != "both":
            return "N/A (Endpoint Missing)"
        
        mismatch_details = []
        for col in parameter_cols:
            val_source = row.get(f"{col}_SOURCE", "")
            val_target = row.get(f"{col}_TARGET", "")
            
            # Treat NaN/None as empty string for comparison
            if val_source == "nan": val_source = ""
            if val_target == "nan": val_target = ""

            if val_source != val_target:
                mismatch_details.append(col)
        
        if not mismatch_details:
            return "MATCH"
        else:
            return f"MISMATCH in: {', '.join(mismatch_details)}"

    merged["Content_Match_Status"] = merged.apply(check_content_match, axis=1)

    # 7. Final "FOUND/MISSING" Summary Column (Requested by User)
    # Logic: If it exists in Target (either 'both' or 'right_only'), it is FOUND. 
    # If it is 'left_only', it is MISSING.
    merged["Final_Availability"] = merged["_merge"].apply(
        lambda x: "MISSING" if x == "left_only" else "FOUND"
    )

    # 8. Clean up and Reorder Columns for Report
    # Move key status columns to the front
    base_cols = ["Endpoint", "Final_Availability", "Presence_Status", "Content_Match_Status"]
    
    # Add the side-by-side parameter columns
    dynamic_cols = []
    for col in parameter_cols:
        if f"{col}_SOURCE" in merged.columns: dynamic_cols.append(f"{col}_SOURCE")
        if f"{col}_TARGET" in merged.columns: dynamic_cols.append(f"{col}_TARGET")
    
    final_cols = base_cols + dynamic_cols
    
    # Filter only columns that actually exist in the merged dataframe
    existing_cols = [c for c in final_cols if c in merged.columns]
    final_df = merged[existing_cols]

    # 9. Save to Excel
    os.makedirs(REPORT_DIR, exist_ok=True)
    try:
        with pd.ExcelWriter(OUTPUT_FILE, engine="openpyxl", mode="w") as writer:
            final_df.to_excel(writer, sheet_name="Comparison_Result", index=False)
        print(f"✅ Success! Report generated: {OUTPUT_FILE}")
    except Exception as e:
        print(f"❌ Failed to write output: {e}")

if __name__ == "__main__":
    compare_endpoints()
